# Generated by Django 4.2.7 on 2025-09-28 09:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin')], default='customer', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('subscription_start_date', models.DateField()),
                ('subscription_end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='milk_app.user')),
            ],
            options={
                'db_table': 'user_subscriptions',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('daily_liters', models.DecimalField(decimal_places=2, max_digits=5)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_rates', to='milk_app.usersubscription')),
            ],
            options={
                'db_table': 'subscription_rates',
                'ordering': ['-effective_from'],
                'unique_together': {('subscription', 'effective_from')},
            },
        ),
        migrations.CreateModel(
            name='DailySkipRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skip_date', models.DateField()),
                ('reason', models.CharField(choices=[('traveling', 'Traveling'), ('excess_stock', 'Have Excess Stock'), ('health', 'Health Reasons'), ('other', 'Other')], default='other', max_length=20)),
                ('notes', models.TextField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skip_requests', to='milk_app.user')),
            ],
            options={
                'db_table': 'daily_skip_requests',
                'unique_together': {('user', 'skip_date')},
            },
        ),
        migrations.CreateModel(
            name='DailyMilkRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_date', models.DateField()),
                ('liters', models.DecimalField(decimal_places=2, max_digits=5)),
                ('milk_type', models.CharField(choices=[('buffalo', 'Buffalo'), ('cow', 'Cow')], default='buffalo', max_length=10)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('delivered', 'Delivered')], default='confirmed', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_requests', to='milk_app.user')),
            ],
            options={
                'db_table': 'daily_milk_requests',
                'unique_together': {('user', 'target_date')},
            },
        ),
        migrations.CreateModel(
            name='DailyMilkDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delivery_date', models.DateField()),
                ('scheduled_liters', models.DecimalField(decimal_places=2, max_digits=5)),
                ('actual_liters', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('skipped', 'Skipped by User'), ('delivered', 'Delivered'), ('failed', 'Delivery Failed')], default='scheduled', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate_applied', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='milk_app.subscriptionrate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='milk_app.user')),
            ],
            options={
                'db_table': 'daily_milk_deliveries',
                'unique_together': {('user', 'delivery_date')},
            },
        ),
    ]
