# Generated by Django 4.2.7 on 2025-11-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymilkdelivery',
            name='reason',
            field=models.TextField(blank=True, help_text='Optional reason for failed delivery or other status changes', max_length=500, null=True),
        ),
    ]
