# Generated by Django 4.2.7 on 2025-11-17 01:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('milk_app', '0002_dailymilkdelivery_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkPricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('liters', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'milk_pricing',
                'ordering': ['liters', '-effective_from'],
            },
        ),
    ]
