# Generated by Django 4.2.7 on 2025-11-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_app', '0003_milkpricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='milk_type',
            field=models.CharField(choices=[('buffalo', 'Buffalo'), ('cow', 'Cow')], default='buffalo', max_length=10),
        ),
    ]
