# Generated by Django 4.2.7 on 2025-11-23 14:46

from django.db import migrations, models


def delete_old_pricing_records(apps, schema_editor):
    """Delete old pricing records before applying new unique constraint"""
    MilkPricing = apps.get_model('milk_app', 'MilkPricing')
    # Delete all old records since we're changing the pricing model completely
    MilkPricing.objects.all().delete()


def reverse_delete_old_pricing_records(apps, schema_editor):
    """Reverse migration - nothing to restore"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('milk_app', '0004_usersubscription_milk_type'),
    ]

    operations = [
        # Update model options first
        migrations.AlterModelOptions(
            name='milkpricing',
            options={'ordering': ['milk_type', '-effective_from']},
        ),
        # Add milk_type field (with default 'buffalo' for existing records)
        migrations.AddField(
            model_name='milkpricing',
            name='milk_type',
            field=models.CharField(choices=[('buffalo', 'Buffalo'), ('cow', 'Cow')], default='buffalo', max_length=10),
        ),
        # Update liters field default
        migrations.AlterField(
            model_name='milkpricing',
            name='liters',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        # Delete old pricing records (they all have same effective_from, causing unique constraint violation)
        migrations.RunPython(delete_old_pricing_records, reverse_delete_old_pricing_records),
        # Add new unique constraint after deleting old records
        migrations.AlterUniqueTogether(
            name='milkpricing',
            unique_together={('milk_type', 'effective_from')},
        ),
    ]
