# Generated by Django 4.2.7 on 2026-01-09 16:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('milk_app', '0005_alter_milkpricing_options_milkpricing_milk_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('delivery_partner', 'Delivery Partner')], default='customer', max_length=20),
        ),
        migrations.CreateModel(
            name='CustomerDeliveryMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_mappings', to='milk_app.user')),
                ('delivery_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_customers', to='milk_app.user')),
            ],
            options={
                'db_table': 'customer_delivery_mappings',
                'ordering': ['-created_at'],
                'unique_together': {('customer', 'delivery_partner')},
            },
        ),
    ]
